### ISSUE TITLE
Multipart upload missing the boundary header

### ISSUE THREAD

**Issue by dgnthr** [oazapfts/oazapfts#512] opened 2023-11-07 07:51 UTC
Hi,

when I generate a multipart upload I can't post it to my server due to the missing header "boundary". The header that gets generated is just `'Content-Type': 'multipart/form-data'`. Using for example Insomnia to generate the same request gives something like `'Content-Type': 'multipart/form-data; boundary=---011000010111000001101001'`. When using fetch directly the same behavior occurs. With fetch you have to explicitly not set the header and let the browser generate it for you. In my case this does not work:

```const form = new FormData();
  form.append("file", file);

  const options_ = {
    method: "PUT",
    body: form,
    headers: { "Content-Type": multipart/form-data },
  };

  return fetch("/api/v1/files/", options_)
```
but this does

```
const form = new FormData();
  form.append("file", file);

  const options_ = {
    method: "PUT",
    body: form,
  };

  return fetch("/api/v1/files/", options_)
```

In the second case the header is generated by the browser. Also see [here](https://muffinman.io/blog/uploading-files-using-fetch-multipart-form-data/) or [here](https://stackoverflow.com/questions/39280438/fetch-missing-boundary-in-multipart-form-data-post). Some time ago this was working fine.

Thank you for your time!

**Comment by helt** [comment] 2023-11-23 16:03
I was just about to open an issue about this. I can confirm this issue

**Comment by bdm-k** [comment] 2023-12-10 09:51
The same issue occurs in node.

**Comment by bdm-k** [comment] 2023-12-10 16:47
I removed the Content-Type header before submitting a request, but encounted an `EPIPE` error of the write(2). What's strange is that, according to the backend output, it seems to be working fine. Currently, I'm using `open-api-mocker` as the backend server. Perhaps I should consider testing with a proper server instead of the  mock server provided by `open-api-mocker`.

Here is the output from the backend:
```
[INFO ] > [POST] /v2/pet/5/uploadImage
[WARN ] Missing application/json content for request body
[INFO ] < [200] {"code":1,"type":"string","message":"string"} (1 ms)
```

**Comment by bdm-k** [comment] 2023-12-11 07:17
I used Django to confirm that removing the Content-Type header is the correct solution. I'm going to try and see if I can somehow write a test script within the scope of open-api-mocker.

**Comment by bdm-k** [comment] 2023-12-12 05:17
I couldn't figure out how to test within the scope of open-api-mocker. But I'm still going to create a PR, since I believe this issue really needs a quick fix.

**Comment by Xiphe** [comment] 2023-12-14 00:24
I've reworked most of our header handling and removed default content types for multipart requests.

Pre-released as `oazapfts@5.0.0-headers.1` might someone be able to validate that it solves this issue?

**Comment by bdm-k** [comment] 2023-12-20 23:58
I can confirm that it is working properly.

**Comment by dgnthr** [comment] 2024-01-08 13:35
Great, the prerelease version works perfectly! Thank you!

**Closed** 2024-01-08 14:23 UTC
Labels: help wanted
